### ISSUE TITLE
[DISCUSSION] - General appearance of flow of the web app

### ISSUE THREAD

**Issue by rase-rocks** [rase-rocks/byw#6]
Taking a cue from the existing byw website the home page should likely be based around a map. I would lean towards using Mapbox to style OpenStreetMap data. Some sort of search function would then be required, likely the search will identify the type of search, coordinates, postcode, address, what3words etc.

**Comment by rase-rocks** [comment]
As of this morning the home page has a nearly full page map with a sidebar to allow for the user to search for places by name location etc. The mapping is OpenStreetMap and the glue is Leaflet.js. Some hacking has had to take place to allow Leaflet to be rendered server side. Check the source for the detail

**Comment by breatheyourwelsh** [comment]
Traditionally the home page will be an introduction to the site from which every other page can be reached. On a computer I would expect the map to be bookmarked not the home page. On an App then directly to the map.

**Comment by rase-rocks** [comment]
Whilst considering other uses for the data we collect I had the idea of a heatmap view. We just need to retain snapshots of our working dataset when changes are made. In the first stages it would be a useful visualisation of how our coverage is improving and then after that give an insight into the language usage generally. It would of course suffer from significant bias for this purpose, but it would be interesting at least.

**Comment by rase-rocks** [comment]
The website is beginning to take shape
