### ISSUE TITLE
[DISCUSSION] - Limiting indexed locations to a specific area

### ISSUE THREAD

**Issue by rase-rocks** [rase-rocks/byw#7]
Do we allow places of interest to be added to our index that are not within the bounds of Wales? A pro for this would be it would limit the usefulness of any old shop adding themselves for some free visibility, but it would also prevent locations in other countries from signing up. It could be quite good to see places around the world that support the language.

**Comment by breatheyourwelsh** [comment]
Certainly England. Preferably no limit geographically.

**Comment by rase-rocks** [comment]
We could then have no geo bounding limit for places to be included. This hints that the submission process for a place to be added to our index be curated.  So, we could have a 'submit yourself' workflow where a location owner can add themselves to the index, but before being accepted the submission is put through a process. 

The process itself could be something alone the lines of an automated check for some requirements to be validated followed by a manual, human, final say. We could implement a queue for auto validated requests that are awaiting manual checking with notification via email to those allowed to do the checks.

Which brings the question who would do this? Ideally a community / committee / selected moderator based scheme could be implemented so that the responsibility is spread across volunteers.

**Comment by rase-rocks** [comment]
The system has moved on and is now automated. The website facilitates the submission of a premises with coordinates and uses a weighted average of all the submissions for a premises to reach the final value
